DROP TABLE IF EXISTS pokemons;
DROP TABLE IF EXISTS trainers;

CREATE TABLE trainers (
  trainer_id SERIAL PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE pokemons (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  cp TEXT NOT NULL
);
